#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/product_management
#    username: root
#    password: 1234
  spring:
    profiles:
      active: prod